blank_issues_enabled: true
contact_links:
  - name: 🥷 Support
    url: https://erlanger.slack.com/archives/C05KJHDJJUF
    about: Please use our Slack channel to ask the community for help. If you are not a member of the Erlanger Slack, request an invitation at https://erlef.org/slack-invite/erlanger
