[buck]
enabled = true
build_deps = false
included_targets = [ "fbcode//whatsapp/elp/test_projects/buck_bad_config/..." ]
source_root = "whatsapp/elp/test_projects/buck_bad_config"

[eqwalizer]
enable_all = false
