[alias]
xtask = "run --package xtask --"

# @fb-only: [build]
# @fb-only: target-dir = "../../../buck-out/elp"

[profile.release]
lto = "thin"
debug = "line-tables-only"

# Workaround to easily locate workspace root
# See https://github.com/rust-lang/cargo/issues/3946
[env]
CARGO_WORKSPACE_DIR = {value = "", relative = true}
