[buck]
enabled = true
build_deps = false
included_targets = [ "fbcode//whatsapp/elp/test_projects/parse_error/..." ]
source_root = "whatsapp/elp/test_projects/parse_error"

[eqwalizer]
enable_all = false
